### ISSUE TITLE
Pip install gateway framework complains about missing assets

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayFramework#10]
`error: can't copy 'waves_gateway/static/assets': doesn't exist or not a regular file`

Pip install on a ubuntu 16.04 gives above error.

**Comment by henning96** [comment]
I have now tested it on Ubuntu 17.10 and it works as expected. The assets folder is part of the distribution as you can see here: https://files.pythonhosted.org/packages/84/ce/c3afc300fab88ebac85159170d393e69fdc72f2ac25a08144a8f8146e02c/waves_gateway-1.0.1.tar.gz. So, this may simply be a problem with your pip installation.

**Comment by jansenmarc** [comment]
Solved?

**Comment by Cleberw3b** [comment]
Hi guys, I'm trying to install the framework but getting the error
`error: can't copy 'waves_gateway/static/assets': doesn't exist or not a regular file`
I'm using python 3.5.2
Also I noticed that the folder assets is not in the repository.
https://github.com/jansenmarc/WavesGatewayFramework/tree/master/waves_gateway
