### ISSUE TITLE
Firefox textbox copy-paste glitches[BUG][FRONT-END]

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayFramework#11]
Firefox only allows 1 time copy pasting.
After that it glitches and the user can't copy paste his generated addr anymore.
This was reported by a user from me, and I could redo this.
Firefox browser, normal addr create.
After 1 time copy paste, impossible to select.

**Comment by PyWaves** [comment]
Please report the version of Firefox and operating system you run on. Is it working on other browsers?

**Comment by BlackTurtle123** [comment]
Firefox tested and glitching:
-Windows 10: Release 59
-Fedora (latest): Release 58.0.2

Confirming it's working on Google chrome on both operating systems.

**Comment by PyWaves** [comment]
Seems to be a bug in Firefox then. Use Chrome instead!

**Comment by BlackTurtle123** [comment]
Can't it be replaced by something that doesn't bug for firefox? 
Since in my test audience from 10 people, 3 used firefox.
So if we have 30% that will have issues, it isnt the most user friendly thing, not sure if it's possible to fix tho.

**Comment by PyWaves** [comment]
Honestly, i don't see that we can afford to put this effort as long as it is limited to one browser version.

**Comment by henning96** [comment]
This is a bug. Copying to clipboard is actually not possible from an disabled input: https://stackoverflow.com/questions/8876928/allow-copy-paste-in-a-disabled-input-text-box-in-firefox-browsers. It does not work in Firefox because it is the only browser that behaves like the spec.
