### ISSUE TITLE
[Question][Feature][Extending] Waves based networks as native platform instead waves

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayFramework#15]
Hello!
Yesterday there was pywaves support for all waves based networks.
Now is my question, how hard would it be to do the same for the gateway?
I screened through the code and I saw that you are heavy depending on mainnet/testnet and that it is hard to overwrite this stuff without changing the framework every time.

So my q is, would it be a hard task to make it support all waves networks?
In Pywaves we can now do this:
py.setNode("https://privatenode.blackturtle.eu","TurtleNetwork", "L")

**Comment by henning96** [comment]
Hi @BlackTurtle123, if you simply want the Gateway to set a specific chainId in its setNode call that would be quite easy to realize.

We are not depending on mainnet/testnet. You can specify any waves_chain you want in your config file. You would have to overwrite the waves web links for the frontend. There are already options for that in the Gateway class constructor.

**Comment by BlackTurtle123** [comment]
Can you also specify non defined pywaves chains? I didn't see how I would pass-over the chain_char  ('L')

**Comment by henning96** [comment]
Because setting the chain_id is not supported right now (the third parameter of setNode). I will add support for that, soon.

**Comment by BlackTurtle123** [comment]
Yes that was what I ment!
Thanks!

**Comment by henning96** [comment]
Added in Release v1.0.3
