### ISSUE TITLE
Not sure what to do

### ISSUE THREAD

**Issue by CryptoLover705** [jansenmarc/WavesGatewayFramework#25]
Hello I did the test gateway but what do I do for this one? can you help me please

**Comment by CryptoLover705** [comment]
I am wanting to add my coin but I am not sure what to do for this version, If you could help me it would be greatly appreciated

**Comment by jansenmarc** [comment]
Which coin do you want to add?

**Comment by CryptoLover705** [comment]
I would like to add SmartCryptoTech

**Comment by jansenmarc** [comment]
Looks like a Bitcoin clone. You should basically be able to use the WavesGatewayLTCExample and connect it to your SmartCryptoTechd.

**Comment by CryptoLover705** [comment]
Ok thank you I will give that a try

**Comment by CryptoLover705** [comment]
Where it says default port I put my coins port right?

**Comment by jansenmarc** [comment]
This is not the place for support. Please join the corresponding Waves TG or Discord groups.
