### ISSUE TITLE
API enhancement

### ISSUE THREAD

**Issue by henning96** [jansenmarc/WavesGatewayFramework#7]
With those optimizations a Gateway may be created like this:

```Python
import waves_gateway as gw


custom_dependency = gw.InjectionToken("custom_dependency")

@gw.Factory(provides=custom_dependency)
def createCustomDependency():
    return something

@gw.Injectable(depends=[custom_dependency], provides=gw.TransactionService)
class CustomTransactionService(gw.TransactionService):
    # implementation
    pass

# may be used to override some special tokens
gw.set(gw.API_KEY, "some custom api key")
gw.set(gw.CUSTOM_CURRENCY_NAME, "custom currency")

gw.run() # will block the execution and start the Gateway
```
## Motivation
This enhancement is meant to simplify the creation of a Gateway, reduce the LOC, but also offer more control. It is possible to override certain services of the Framework. But it is only possible to override services which injection token is exposed by the Framework. This allows to have private services that cannot be changed. The user will be provided with custom error messages of which providers he is required to specify and a description of those (docstring where available).
Custom services will be able to define dependencies to Framework exposed services and custom ones. For example, most currencies will have some kind of proxy to the node. This could be provided automatically.

## How it works
The Framework exposes a child injector to the custom code that may be used to define a variety of tokens required.
The Injectable decorator is already in use in the Framework. The exposed one would use the global child injector. Same with the Factory decorator.
The `set` method is a shortcut for the set method of the child injector.
The `run` method handles the complete startup. It includes the monkey patching, loads a configuration file if any and creates a Gateway instance with the child injector.

## What is a child injector
It has a small but important difference to the Angular hierarchical injector (for those who know Angular).
A child injector has a reference to the global injector that already exists.
It has the same functionality as the global injector.
But, if a token is demanded that the child injector does not know about, the parent injector is asked about it. The required information will be fetched and the instance is created **in** the child injector. So, the parent injector does not know about the instance. This has the advantage that everything that is defined in the child injector overrides the parent injectors tokens.

## Compatibilty
The old API will still work. What changes is the behavior of the already exposed injector. Which, as far as I know, no one uses.

**Comment by PyWaves** [comment]
Looks great, but i can't find a corresponding pull request...

**Comment by henning96** [comment]
I have now tested this approach on the Waves-Ripple-Gateway. The LOC of the Gateway can be reduced by about 37% (with the same functionality): 203 LOC -> 128 LOC.
With this approach, the only line all Gateways have in common is: `gw.run()`. That's it. So, the percentage of non-currency specific code is below 1%.

**Comment by PyWaves** [comment]
Perfect, go ahead...
