### ISSUE TITLE
Convert from a 2 digit to a 8 digit network

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayFramework#8]
Hello!
Here I am again...
I heard there should be a setting somewhere that makes it possible to easy convert from a 2 digit network to a 8 digit network, what setting is this?
Thanks in advance

**Comment by PyWaves** [comment]
Seems to be in https://github.com/jansenmarc/WavesGatewayLTCExample/blob/master/waves_litecoin_gateway/litecoin_gateway.py, line 22 and 23.

**Comment by BlackTurtle123** [comment]
Well this works when both are the same, 1 direction is always broken
when I put it at 8 the other half works, when at 2, the other half works
so when 2 I can send from waves to my network, when at 8 I can send from my network to waves

**Comment by henning96** [comment]
It is possible to define a second IntegerConverterService for this case.
It is called asset_integer_converter_service in the Gateway class constructor.
By default this one, does nothing. Which means it simply returns the value it is given.
But you may overwrite this behaviour with your own conversion logic.

**Comment by BlackTurtle123** [comment]
Thanks!I guess those contains the same 2 methods as the current one, just one is with 8 other is with 2 digits?-------- Oorspronkelijk bericht --------Onderwerp: Re: [jansenmarc/WavesGatewayFramework] Convert from a 2 digit to a 8 digit network (#8)Van: Henning Gerrits Aan: jansenmarc/WavesGatewayFramework Cc: "Bram N." ,Author It is possible to define a second IntegerConverterService for this case.
It is called asset_integer_converter_service in the Gateway class constructor.
By default this one, does nothing. Which means it simply returns the value it is given.
But you may overwrite this behaviour with your own conversion logic.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jansenmarc/WavesGatewayFramework","title":"jansenmarc/WavesGatewayFramework","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jansenmarc/WavesGatewayFramework"}},"updates":{"snippets":[{"icon":"PERSON","message":"@henning96 in #8: It is possible to define a second IntegerConverterService for this case.\r\nIt is called asset_integer_converter_service in the Gateway class constructor.\r\nBy default this one, does nothing. Which means it simply returns the value it is given.\r\nBut you may overwrite this behaviour with your own conversion logic."}],"action":{"name":"View Issue","url":"https://github.com/jansenmarc/WavesGatewayFramework/issues/8#issuecomment-381352787"}}}

**Comment by henning96** [comment]
It is the same class, so it has the same two methods. One for converting to a Waves Asset value and back.
Before sending asset the revert_amount_conversion method is called.
And when receiving any asset the convert_amount_to_int method is called.

**Comment by BlackTurtle123** [comment]
When I use the round method, it seems to round the numbers correctly until a certain height.
`3NNs7aoW8bJMvoB5tuLurLamXAVHoqNAEVj
49999999999
{'type': 4, 'id': 'E6nLCwEvPqTd7DAduYAAS42d8BdJGKpr1TorRYzE2Ag9', 'sender': '3NP1rd5L7Uo35VutjuQWsKF9LbVzWoKp367', 'senderPublicKey': '3dG1MJmxQExqor5aneG5pL7mAXMuT7wqAYexGzaqsJjm', 'fee': 200000, 'timestamp': 1523745228333, 'signature': '2dXkcE9Rj5BMvo7RTSCNzvs2JeUZx7g9iZFQ9ZjdxASYKVRqMGha95U9Uy44hbS3e3Vu8JZywAXYmVYHaDnUdG32', 'recipient': '3NNs7aoW8bJMvoB5tuLurLamXAVHoqNAEVj', 'assetId': None, 'amount': 49999799999, 'feeAsset': None, 'attachment': ''}
printing on waves chain 49999.99999994
printing on waves chain 0.00100000`

The gateway is trying to send 500TN to the mainnet (499,99) seems pretty accurate, however, instead rounding it, he ads 8 digits to it.. He also reduces the fees from the smallest unit, while my fees in the conf are set at : 
coin = 0.05000000
gateway = 0.01000000
My class is this, am I messing up something/ not doing enough?:
`class TurtleNodeIntegerConverterService(gw.IntegerConverterService):
    """
    """

    def __init__(self, tn_factor: int, tn_round_precision: int) -> None:
        self._tn_factor = tn_factor
        self._tn_round_precision = tn_round_precision

    def convert_amount_to_int(self, amount: Decimal) -> int:
        return gw.convert_to_int(amount, self._tn_factor)

    def revert_amount_conversion(self, amount: int) -> Number:
        return gw.convert_to_decimal(amount, self._tn_factor, self._tn_round_precision)`

**Comment by BlackTurtle123** [comment]
How are the fees calculated on the waves chain?
Since they are put in place as 0.001 and not as 100000 in the framework, am I missing another converter somewhere else?

**Comment by BlackTurtle123** [comment]
Okay, I had a small workaround on my pc now.
I am now building my waves fork code, hopefully by the time I can go live with the gateway this bug is solved so I don't need to mess with the package files anymore on my server.
It's really cool to see the final pieces comming together!

**Comment by henning96** [comment]
What kind of workaround are you using exactly?

**Comment by BlackTurtle123** [comment]
just doing the fee *100000000 (or 10^8)

**Comment by henning96** [comment]
This has been fixed in Release 1.0.1.
